apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-scheduler
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kube-scheduler
        image: k8s.gcr.io/kube-scheduler-amd64:v1.16.2
        imagePullPolicy: IfNotPresent
        command: 
        - kube-scheduler
        - --leader-elect=true
        - --bind-address=127.0.0.1
        - --kubeconfig=/opt/kubernetes/kubeconfig
        livenessProbe:
          failureThreshold: 8
          httpGet:
            host: 127.0.0.1
            path: /healthz
            port: 10251
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        volumeMounts:
        - mountPath: /opt/kubernetes
          name: kubeconfig
          readOnly: true
      volumes:
      - name: kubeconfig
        configMap:
          name: kube-scheduler
      # The CA which signs the kube-apiserver certificate
      - name: kube-apiserver-certs
        secret:
          secretName: kube-apiserver-public
          defaultMode: 0400
          items:
          - key: ca.crt
            path: ca.crt
      # The TLS keys for internal cluster comms
      - name: kube-scheduler-certs
        secret:
          secretName: kube-scheduler-private
          defaultMode: 0400