version: "3.7"
services:

  kube-apiserver:
    image: k8s.gcr.io/kube-apiserver-amd64:v1.15.3
    command: 
      - kube-apiserver
      - --etcd-servers=localhost:1234
    ports:
      - "6443"
    networks:
      - kube-master

networks:
  kube-master:
