version: "3.7"
services:

  bootstrap-certs:
    image: hashicorp/terraform
    init: true
    environment:
      TF_IN_AUTOMATION: 1
    entrypoint: /bin/sh
    command:
      - -c
      - |
        # check to see if certs
        cd /tf
        terraform -version
        terraform init
        terraform plan -out tfplan
        terraform apply tfplan

        cd output/
        cp -v apiserver_*.pem ca_public.pem service-account-ca_public.pem /certs/apiserver/
    volumes:
      - ./certs:/tf
      - certs-apiserver:/certs/apiserver

  bootstrap-token:
    image: busybox
    init: true
    command:
      - sh
      - -c
      - |
        TOKEN=$$(head -c 16 /dev/urandom | od -An -t x | tr -d ' ')
        echo "$${TOKEN},dummy,10001,\"system:bootstrappers\"" > /token-data/temporary-tokens
        echo "Token: $${TOKEN}"
    volumes:
      - token-data:/token-data

  kube-apiserver:
    restart: always
    # https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/kube-apiserver-amd64
    image: k8s.gcr.io/kube-apiserver-amd64:v${KUBE_VERSION:-1.15.3}
    command: 
      - kube-apiserver
      - --etcd-servers=http://etcd:2379
      #- --authorization-mode=RBAC
      - --token-auth-file=/token-data/temporary-tokens
      - --client-ca-file=/run/config/pki/ca_public.pem
      - --kubelet-certificate-authority=/run/config/pki/ca_public.pem
      - --kubelet-client-certificate=/run/config/pki/apiserver_public.pem
      - --kubelet-client-key=/run/config/pki/apiserver_private.pem
      - --kubelet-https=true
      - --service-account-key-file=/run/config/pki/service-account-ca_public.pem
      - --tls-cert-file=/run/config/pki/apiserver_public.pem
      - --tls-private-key-file=/run/config/pki/apiserver_private.pem
    ports:
      - ${KUBE_APISERVER_PORT:-6443}:6443
    volumes:
      - token-data:/token-data
      - certs-apiserver:/run/config/pki
    networks:
      - kube-master
    depends_on:
      - bootstrap-certs
      - bootstrap-token
      - etcd

  etcd:
    restart: always
    # https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/etcd-amd64
    image: k8s.gcr.io/etcd-amd64:${ETCD_VERSION:-3.3.15}
    command:
      - etcd
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
      - --data-dir=/var/lib/etcd
    ports:
      - "2379"
    volumes:
      - etcd-data:/var/lib/etcd
    networks:
      - kube-master
    depends_on:
      - bootstrap-certs

networks:
  kube-master:

volumes:
  token-data:
  etcd-data:
  certs-apiserver: