apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-apiserver.fullname" . }}
  labels:
{{ include "kube-apiserver.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kube-apiserver.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kube-apiserver.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - kube-apiserver
          - --etcd-servers=http://{{ .Release.Name }}-etcd:2379
          - --authorization-mode=Node,RBAC
          # - --client-ca-file=/run/config/pki/ca_public.pem
          # - --kubelet-certificate-authority=/run/config/pki/ca_public.pem
          # - --kubelet-client-certificate=/run/config/pki/apiserver_public.pem
          # - --kubelet-client-key=/run/config/pki/apiserver_private.pem
          - --kubelet-https=true
          #- --bind-port=8443
          # - --service-account-key-file=/run/config/pki/service-account-ca_public.pem
          # - --tls-cert-file=/run/config/pki/apiserver_public.pem
          # - --tls-private-key-file=/run/config/pki/apiserver_private.pem
          ports:
            - name: kube-apiserver
              containerPort: 6443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: kube-apiserver
              scheme: HTTPS
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /healthz
              port: kube-apiserver
              scheme: HTTPS
            initialDelaySeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
