commonLabels:
  system: kubernetes-master
  app: etcd
resources:
- statefulset.yml
- service-headless.yml
- service-discovery.yml
- peer_certificate.yml
configurations:
- kustomizeconfig.yml
vars:
- name: ETCD_STATEFULSET_NAME
  objref:
    kind: StatefulSet
    name: etcd
    apiVersion: apps/v1
- name: ETCD_HEADLESS_SERVICE_NAME
  objref:
    kind: Service
    name: etcd-headless
    apiVersion: v1
- name: ETCD_DISCOVERY_SERVICE_NAME
  objref:
    kind: Service
    name: etcd-discovery
    apiVersion: v1
- name: ETCD_PEER_CERT_SECRET_NAME
  objref:
    kind: Certificate
    name: etcd-peers
    apiVersion: cert-manager.io/v1alpha2
  fieldref:
    fieldpath: spec.secretName