apiVersion: v1
kind: Service
metadata:
  name: etcd-headless
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: client
    port: 2379
    targetPort: client
    protocol: TCP
  - name: peer
    port: 2380
    targetPort: peer
    protocol: TCP
  selector:
    app.kubernetes.io/name: etcd