dependencies:
  - name: etcd
    version: ">=1.0.0"
    # Temporary until we're up and running, then we can move to a more robust etcd chart
    repository: file://./subcharts/etcd
    condition: etcd.enabled
  - name: kube-apiserver
    version: ">=1.0.0"
    repository: file://./subcharts/kube-apiserver
    condition: kube-apiserver.enabled