apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: kube-apiserver
    port: 6443
    targetPort: kube-apiserver
    protocol: TCP
  selector:
    app.kubernetes.io/name: kube-apiserver