apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  template:
    spec:
      containers:
      - name: etcd
        volumeMounts:
        - mountPath: /var/lib/etcd/data
          name: etcd-data
      volumes:
      - name: etcd-data
        emptyDir: {}
 