
nameReference:
- kind: Certificate
  apiVersion: cert-manager.io/v1alpha2
  fieldSpecs:
  - path: spec/secretName
- kind: Issuer
  apiVersion: cert-manager.io/v1alpha2
  fieldSpecs:
  - path: spec/ca/secretName