apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: private-ca
spec:
  secretName: private-ca
  commonName: "Kubernetes Private CA"
  keyAlgorithm: ecdsa
  keySize: 384
  isCA: true
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer
