apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: public-ca
spec:
  secretName: public-ca
  commonName: "Kubernetes Public CA"
  isCA: true
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer
