apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}-headless
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
{{ include "etcd.labels" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: client
      port: {{ .Values.service.port }}
      targetPort: client
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "etcd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
