apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cluster-cert-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cluster-cert-manager
    spec:
      serviceAccountName: cluster-cert-manager-sa
      containers:
        - name: cert-manager
          image: quay.io/jetstack/cert-manager-controller@sha256:9c442079a9c5d87d67d9c9b76f43ab66654ab38e8c24c649a397d64ccd46c0aa # For client auth key usage
          imagePullPolicy: IfNotPresent
          args:
          - --cluster-resource-namespace=$(POD_NAMESPACE)
          - --leader-election-namespace=$(POD_NAMESPACE)
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
       