apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  template:
    spec:
      containers:
      - name: etcd
        env:
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: "http://$(POD_NAME).local-etcd-headless:2379"
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: "http://$(POD_NAME).local-etcd-headless:2380"
        # - name: ETCD_INITIAL_CLUSTER
        #   value: local-etcd-0=http://local-etcd-0.local-etcd-headless:2380,local-etcd-1=http://local-etcd-1.local-etcd-headless:2380,local-etcd-2=http://local-etcd-2.local-etcd-headless:2380