apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kube-apiserver
spec:
  template:
    spec:
      containers:
      - name: kube-apiserver
        env:
        - name: ETCD_URL
          value: "http://local-etcd-discovery:2379"